### ISSUE TITLE
Error finding platform: TypeError: generateKeyPairSync is not a function

### ISSUE THREAD

**Issue by GreenOn** [SanDiegoCodeSchool/lti-node-example#1]
Hi there!
I am following your instructions and after `npm start`, I am getting an error on console log `Error finding platform: TypeError: generateKeyPairSync is not a function`. 
It seems Moodle updated their URL for sandbox from demo.moodle to sandbox.moodledemo.net. 

I tried with the below settings, but still no luck:

`registerPlatform(
  'https://sandbox.moodledemo.net',
  'moodle',
  '8xxxxxxxxxx',
  'https://sandbox.moodledemo.net/mod/lti/auth.php',
  'https://sandbox.moodledemo.net/mod/lti/token.php',
  'http://xxxxxxxx.ngrok.io/project/submit',
  { method: 'JWK_SET', key: 'https://sandbox.moodledemo.net/mod/lti/certs.php' }
);
`
Could you anyone throw some insights into this, please? Thank you!

**Comment by GreenOn** [comment]
Just found out that I had to update my node version and moved past this.
 I am able to get the public key but still no luck on project/submit and I get the following error:
```
TypeError: C:\Users\xyz\lti-node-example\views\submit.ejs:53
    51|   <div class="text-center">

    52|     <h3 id='projectName'>

 >> 53|       <% if ((payload['https://purl.imsglobal.org/spec/lti/claim/context'] != null) && payload['https://purl.imsglobal.org/spec/lti/claim/context'].label != null) { %>

    54|         <%= payload['https://purl.imsglobal.org/spec/lti/claim/context'].label %>

    55|       <% } %>

    56|       <% if (payload['https://purl.imsglobal.org/spec/lti/claim/context'] != null && payload['https://purl.imsglobal.org/spec/lti/claim/context'].title != null) { %>


Cannot read property 'https://purl.imsglobal.org/spec/lti/claim/context' of undefined
    at eval (eval at compile (C:\Users\xyz\lti-node-example\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:9:20)
    at returnedFn (C:\Users\xyz\lti-node-example\node_modules\ejs\lib\ejs.js:668:17)
    at tryHandleCache (C:\Users\xyz\lti-node-example\node_modules\ejs\lib\ejs.js:254:36)
    at View.exports.renderFile [as engine] (C:\Users\xyz\lti-node-example\node_modules\ejs\lib\ejs.js:485:10)
    at View.render (C:\Users\xyz\lti-node-example\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\xyz\lti-node-example\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\xyz\lti-node-example\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\xyz\lti-node-example\node_modules\express\lib\response.js:1012:7)
    at C:\Users\xyz\lti-node-example\server\server.js:126:7
    at Layer.handle [as handle_request] (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\xyz\lti-node-example\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\xyz\lti-node-example\node_modules\express\lib\router\index.js:275:10)
```

**Comment by doldsimo** [comment]
@GreenOn 
Same here, I don't get it to work..
it always throws an error
